#electricity
wind-on: Onshore Wind
wind-off: Offshore Wind
solar-PV: Solar
bioST: Biomass Steam Turbine
nuclear: Nuclear
SCPC: Coal Power Plant
CCGT-H2: H2-fired Combined-cycle Gas Turbine
OCGT-H2: H2-fired Open-cycle Gas Turbine
CCGT+CC: Combined-cycle Gas Turbine w/CC
CCGT_: Combined-cycle Gas Turbine
OCGT_: Open-cycle Gas Turbine
wasteST: Waste Steam Turbine
oil-eng: Diesel Group
hydro-turbine: Hydro Turbine
RoR: Run-of-River
PH-discharge: Pump Hydro
battery-storage: Battery Charger
# heat
oil-boiler: Diesel Boiler
bio-boiler: Biomass Boiler
gas-boiler: Gas Boiler
coal-boiler: Coal Boiler
air-heatpump: Air HP
air-heatpump-cool: Cooling Unit
ground-heatpump: Ground HP
electric-heating: Electric Heater
PEM: Electrolyzer
SMR: Steam Methane Reforming
REF-SMR: Refinery
REF(H2): Refinery
(BM)FT: Biofuel Production
(H2)FT-DC: Synfuel Production
(COEL)FT-MEA: Synfuel Production
CH4-import: Gas Imports
LNG-terminal: LNG Terminals
gas-extraction: Gas Extractions
bio-diges-up: Bio-digestion and Upgrading
bio-diges-up+CC: Bio-digestion and Upgrading w/CC
harber-bosch: Harber Bosch
methanation: Methanation
(H2)MeOH-DC: Syn-production of Methanol
(BM)MeOH: Bio-production of Methanol